/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit.v:1" *)
module alu_8bit(A, B, ALU_Sel, Cin, Result, Cout, Zero, Negative, Overflow);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit.v:2" *)
  input [7:0] A;
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit.v:4" *)
  input [2:0] ALU_Sel;
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit.v:3" *)
  input [7:0] B;
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit.v:5" *)
  input Cin;
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit.v:8" *)
  output Cout;
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit.v:10" *)
  output Negative;
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit.v:11" *)
  output Overflow;
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit.v:7" *)
  output [7:0] Result;
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit.v:9" *)
  output Zero;
  OAI22_X1 _159_ (
    .A1(A[1]),
    .A2(_117_),
    .B1(_128_),
    .B2(_114_),
    .ZN(_139_)
  );
  AOI21_X1 _160_ (
    .A(_139_),
    .B1(_131_),
    .B2(_130_),
    .ZN(_140_)
  );
  AOI222_X1 _161_ (
    .A1(A[2]),
    .A2(_121_),
    .B1(_132_),
    .B2(_134_),
    .C1(_136_),
    .C2(A[0]),
    .ZN(_141_)
  );
  NAND4_X1 _162_ (
    .A1(_135_),
    .A2(_138_),
    .A3(_140_),
    .A4(_141_),
    .ZN(Result[1])
  );
  NOR2_X1 _163_ (
    .A1(_098_),
    .A2(B[2]),
    .ZN(_142_)
  );
  XOR2_X1 _164_ (
    .A(A[2]),
    .B(B[2]),
    .Z(_143_)
  );
  INV_X1 _165_ (
    .A(_143_),
    .ZN(_144_)
  );
  OAI21_X1 _166_ (
    .A(_137_),
    .B1(_128_),
    .B2(_112_),
    .ZN(_145_)
  );
  XNOR2_X1 _167_ (
    .A(_143_),
    .B(_145_),
    .ZN(_146_)
  );
  OR2_X1 _168_ (
    .A1(_130_),
    .A2(_146_),
    .ZN(_147_)
  );
  XNOR2_X1 _169_ (
    .A(_130_),
    .B(_146_),
    .ZN(_148_)
  );
  OAI21_X1 _170_ (
    .A(_133_),
    .B1(B[1]),
    .B2(_097_),
    .ZN(_149_)
  );
  NAND2_X1 _171_ (
    .A1(_144_),
    .A2(_149_),
    .ZN(_150_)
  );
  XNOR2_X1 _172_ (
    .A(_144_),
    .B(_149_),
    .ZN(_151_)
  );
  AND2_X1 _173_ (
    .A1(A[2]),
    .A2(B[2]),
    .ZN(_152_)
  );
  NOR2_X1 _174_ (
    .A1(A[2]),
    .A2(_117_),
    .ZN(_153_)
  );
  AOI221_X1 _175_ (
    .A(_153_),
    .B1(_143_),
    .B2(_113_),
    .C1(A[1]),
    .C2(_136_),
    .ZN(_154_)
  );
  OAI21_X1 _176_ (
    .A(_111_),
    .B1(B[2]),
    .B2(A[2]),
    .ZN(_155_)
  );
  AOI22_X1 _177_ (
    .A1(A[3]),
    .A2(_121_),
    .B1(_124_),
    .B2(_152_),
    .ZN(_156_)
  );
  AND3_X1 _178_ (
    .A1(_154_),
    .A2(_155_),
    .A3(_156_),
    .ZN(_157_)
  );
  OAI221_X1 _179_ (
    .A(_157_),
    .B1(_151_),
    .B2(_120_),
    .C1(_107_),
    .C2(_148_),
    .ZN(Result[2])
  );
  NAND2_X1 _180_ (
    .A1(_099_),
    .A2(B[3]),
    .ZN(_158_)
  );
  NOR2_X1 _181_ (
    .A1(_099_),
    .A2(B[3]),
    .ZN(_000_)
  );
  XOR2_X1 _182_ (
    .A(A[3]),
    .B(B[3]),
    .Z(_001_)
  );
  INV_X1 _183_ (
    .A(_001_),
    .ZN(_002_)
  );
  AOI21_X1 _184_ (
    .A(_152_),
    .B1(_145_),
    .B2(_143_),
    .ZN(_003_)
  );
  XNOR2_X1 _185_ (
    .A(_002_),
    .B(_003_),
    .ZN(_004_)
  );
  OR2_X1 _186_ (
    .A1(_147_),
    .A2(_004_),
    .ZN(_005_)
  );
  XNOR2_X1 _187_ (
    .A(_147_),
    .B(_004_),
    .ZN(_006_)
  );
  OAI21_X1 _188_ (
    .A(_150_),
    .B1(B[2]),
    .B2(_098_),
    .ZN(_007_)
  );
  XNOR2_X1 _189_ (
    .A(_001_),
    .B(_007_),
    .ZN(_008_)
  );
  NAND2_X1 _190_ (
    .A1(A[3]),
    .A2(B[3]),
    .ZN(_009_)
  );
  NOR2_X1 _191_ (
    .A1(A[3]),
    .A2(_117_),
    .ZN(_010_)
  );
  NOR2_X1 _192_ (
    .A1(_125_),
    .A2(_009_),
    .ZN(_011_)
  );
  AOI221_X1 _193_ (
    .A(_010_),
    .B1(_001_),
    .B2(_113_),
    .C1(A[2]),
    .C2(_136_),
    .ZN(_012_)
  );
  OAI21_X1 _194_ (
    .A(_111_),
    .B1(B[3]),
    .B2(A[3]),
    .ZN(_013_)
  );
  AOI21_X1 _195_ (
    .A(_011_),
    .B1(_121_),
    .B2(A[4]),
    .ZN(_014_)
  );
  NAND3_X1 _196_ (
    .A1(_012_),
    .A2(_013_),
    .A3(_014_),
    .ZN(_015_)
  );
  AOI21_X1 _197_ (
    .A(_015_),
    .B1(_008_),
    .B2(_119_),
    .ZN(_016_)
  );
  OAI21_X1 _198_ (
    .A(_016_),
    .B1(_006_),
    .B2(_107_),
    .ZN(Result[3])
  );
  NOR2_X1 _199_ (
    .A1(_100_),
    .A2(B[4]),
    .ZN(_017_)
  );
  XOR2_X1 _200_ (
    .A(A[4]),
    .B(B[4]),
    .Z(_018_)
  );
  OAI21_X1 _201_ (
    .A(_009_),
    .B1(_003_),
    .B2(_002_),
    .ZN(_019_)
  );
  XNOR2_X1 _202_ (
    .A(_018_),
    .B(_019_),
    .ZN(_020_)
  );
  OR2_X1 _203_ (
    .A1(_005_),
    .A2(_020_),
    .ZN(_021_)
  );
  XNOR2_X1 _204_ (
    .A(_005_),
    .B(_020_),
    .ZN(_022_)
  );
  AOI211_X1 _205_ (
    .A(_142_),
    .B(_000_),
    .C1(_149_),
    .C2(_144_),
    .ZN(_023_)
  );
  OAI21_X1 _206_ (
    .A(_158_),
    .B1(_000_),
    .B2(_007_),
    .ZN(_024_)
  );
  AOI211_X1 _207_ (
    .A(_018_),
    .B(_023_),
    .C1(_099_),
    .C2(B[3]),
    .ZN(_025_)
  );
  XNOR2_X1 _208_ (
    .A(_018_),
    .B(_024_),
    .ZN(_026_)
  );
  NOR2_X1 _209_ (
    .A1(A[4]),
    .A2(_117_),
    .ZN(_027_)
  );
  OAI21_X1 _210_ (
    .A(_111_),
    .B1(B[4]),
    .B2(A[4]),
    .ZN(_028_)
  );
  AND2_X1 _211_ (
    .A1(A[4]),
    .A2(B[4]),
    .ZN(_029_)
  );
  NAND2_X1 _212_ (
    .A1(_124_),
    .A2(_029_),
    .ZN(_030_)
  );
  AOI21_X1 _213_ (
    .A(_027_),
    .B1(_136_),
    .B2(A[3]),
    .ZN(_031_)
  );
  AOI22_X1 _214_ (
    .A1(A[5]),
    .A2(_121_),
    .B1(_018_),
    .B2(_113_),
    .ZN(_032_)
  );
  AND4_X1 _215_ (
    .A1(_028_),
    .A2(_030_),
    .A3(_031_),
    .A4(_032_),
    .ZN(_033_)
  );
  OAI221_X1 _216_ (
    .A(_033_),
    .B1(_026_),
    .B2(_120_),
    .C1(_107_),
    .C2(_022_),
    .ZN(Result[4])
  );
  NAND2_X1 _217_ (
    .A1(A[5]),
    .A2(_103_),
    .ZN(_034_)
  );
  XNOR2_X1 _218_ (
    .A(A[5]),
    .B(B[5]),
    .ZN(_035_)
  );
  AOI21_X1 _219_ (
    .A(_029_),
    .B1(_019_),
    .B2(_018_),
    .ZN(_036_)
  );
  XNOR2_X1 _220_ (
    .A(_035_),
    .B(_036_),
    .ZN(_037_)
  );
  NOR2_X1 _221_ (
    .A1(_021_),
    .A2(_037_),
    .ZN(_038_)
  );
  XNOR2_X1 _222_ (
    .A(_021_),
    .B(_037_),
    .ZN(_039_)
  );
  OAI21_X1 _223_ (
    .A(_035_),
    .B1(_025_),
    .B2(_017_),
    .ZN(_040_)
  );
  NOR3_X1 _224_ (
    .A1(_017_),
    .A2(_025_),
    .A3(_035_),
    .ZN(_041_)
  );
  NAND2_X1 _225_ (
    .A1(_119_),
    .A2(_040_),
    .ZN(_042_)
  );
  NOR2_X1 _226_ (
    .A1(A[5]),
    .A2(_117_),
    .ZN(_043_)
  );
  NAND2_X1 _227_ (
    .A1(A[5]),
    .A2(B[5]),
    .ZN(_044_)
  );
  OR2_X1 _228_ (
    .A1(A[5]),
    .A2(B[5]),
    .ZN(_045_)
  );
  AOI22_X1 _229_ (
    .A1(A[4]),
    .A2(_136_),
    .B1(_045_),
    .B2(_111_),
    .ZN(_046_)
  );
  OAI221_X1 _230_ (
    .A(_046_),
    .B1(_044_),
    .B2(_125_),
    .C1(_114_),
    .C2(_035_),
    .ZN(_047_)
  );
  AOI211_X1 _231_ (
    .A(_043_),
    .B(_047_),
    .C1(A[6]),
    .C2(_121_),
    .ZN(_048_)
  );
  OAI221_X1 _232_ (
    .A(_048_),
    .B1(_042_),
    .B2(_041_),
    .C1(_107_),
    .C2(_039_),
    .ZN(Result[5])
  );
  NOR2_X1 _233_ (
    .A1(_101_),
    .A2(B[6]),
    .ZN(_049_)
  );
  XOR2_X1 _234_ (
    .A(A[6]),
    .B(B[6]),
    .Z(_050_)
  );
  OAI21_X1 _235_ (
    .A(_044_),
    .B1(_036_),
    .B2(_035_),
    .ZN(_051_)
  );
  XOR2_X1 _236_ (
    .A(_050_),
    .B(_051_),
    .Z(_052_)
  );
  AND2_X1 _237_ (
    .A1(_038_),
    .A2(_052_),
    .ZN(_053_)
  );
  XNOR2_X1 _238_ (
    .A(_038_),
    .B(_052_),
    .ZN(_054_)
  );
  NAND3_X1 _239_ (
    .A1(_034_),
    .A2(_040_),
    .A3(_050_),
    .ZN(_055_)
  );
  AOI21_X1 _240_ (
    .A(_050_),
    .B1(_040_),
    .B2(_034_),
    .ZN(_056_)
  );
  NOR2_X1 _241_ (
    .A1(_120_),
    .A2(_056_),
    .ZN(_057_)
  );
  AND2_X1 _242_ (
    .A1(A[6]),
    .A2(B[6]),
    .ZN(_058_)
  );
  NOR2_X1 _243_ (
    .A1(_114_),
    .A2(_058_),
    .ZN(_059_)
  );
  OAI22_X1 _244_ (
    .A1(A[6]),
    .A2(B[6]),
    .B1(_111_),
    .B2(_059_),
    .ZN(_060_)
  );
  AOI22_X1 _245_ (
    .A1(A[5]),
    .A2(_136_),
    .B1(_058_),
    .B2(_124_),
    .ZN(_061_)
  );
  NOR2_X1 _246_ (
    .A1(A[6]),
    .A2(_117_),
    .ZN(_062_)
  );
  AOI21_X1 _247_ (
    .A(_062_),
    .B1(_121_),
    .B2(A[7]),
    .ZN(_063_)
  );
  NAND3_X1 _248_ (
    .A1(_060_),
    .A2(_061_),
    .A3(_063_),
    .ZN(_064_)
  );
  AOI21_X1 _249_ (
    .A(_064_),
    .B1(_057_),
    .B2(_055_),
    .ZN(_065_)
  );
  OAI21_X1 _250_ (
    .A(_065_),
    .B1(_054_),
    .B2(_107_),
    .ZN(Result[6])
  );
  NOR2_X1 _251_ (
    .A1(A[7]),
    .A2(_104_),
    .ZN(_066_)
  );
  XNOR2_X1 _252_ (
    .A(A[7]),
    .B(B[7]),
    .ZN(_067_)
  );
  AOI21_X1 _253_ (
    .A(_058_),
    .B1(_051_),
    .B2(_050_),
    .ZN(_068_)
  );
  XOR2_X1 _254_ (
    .A(_067_),
    .B(_068_),
    .Z(_069_)
  );
  XNOR2_X1 _255_ (
    .A(_053_),
    .B(_069_),
    .ZN(_070_)
  );
  NOR2_X1 _256_ (
    .A1(_049_),
    .A2(_056_),
    .ZN(_071_)
  );
  OR3_X1 _257_ (
    .A1(_049_),
    .A2(_056_),
    .A3(_067_),
    .ZN(_072_)
  );
  OAI21_X1 _258_ (
    .A(_067_),
    .B1(_056_),
    .B2(_049_),
    .ZN(_073_)
  );
  NAND3_X1 _259_ (
    .A1(_119_),
    .A2(_072_),
    .A3(_073_),
    .ZN(_074_)
  );
  NOR2_X1 _260_ (
    .A1(A[7]),
    .A2(B[7]),
    .ZN(_075_)
  );
  NAND2_X1 _261_ (
    .A1(A[7]),
    .A2(B[7]),
    .ZN(_076_)
  );
  AOI21_X1 _262_ (
    .A(_111_),
    .B1(_113_),
    .B2(_076_),
    .ZN(_077_)
  );
  NOR2_X1 _263_ (
    .A1(_075_),
    .A2(_077_),
    .ZN(_078_)
  );
  NAND2_X1 _264_ (
    .A1(A[6]),
    .A2(_136_),
    .ZN(_079_)
  );
  OAI221_X1 _265_ (
    .A(_079_),
    .B1(_076_),
    .B2(_125_),
    .C1(A[7]),
    .C2(_117_),
    .ZN(_080_)
  );
  NOR2_X1 _266_ (
    .A1(_078_),
    .A2(_080_),
    .ZN(_081_)
  );
  OAI211_X1 _267_ (
    .A(_074_),
    .B(_081_),
    .C1(_107_),
    .C2(_070_),
    .ZN(Negative)
  );
  OR4_X1 _268_ (
    .A1(Result[0]),
    .A2(Result[1]),
    .A3(Result[2]),
    .A4(Result[3]),
    .ZN(_082_)
  );
  OR3_X1 _269_ (
    .A1(Result[4]),
    .A2(Result[5]),
    .A3(_082_),
    .ZN(_083_)
  );
  NOR3_X1 _270_ (
    .A1(Result[6]),
    .A2(Negative),
    .A3(_083_),
    .ZN(Zero)
  );
  NOR2_X1 _271_ (
    .A1(_066_),
    .A2(_071_),
    .ZN(_084_)
  );
  AOI21_X1 _272_ (
    .A(_049_),
    .B1(_104_),
    .B2(A[7]),
    .ZN(_085_)
  );
  AOI211_X1 _273_ (
    .A(_049_),
    .B(_056_),
    .C1(A[7]),
    .C2(_104_),
    .ZN(_086_)
  );
  AND2_X1 _274_ (
    .A1(_070_),
    .A2(_076_),
    .ZN(_087_)
  );
  NOR2_X1 _275_ (
    .A1(_070_),
    .A2(_075_),
    .ZN(_088_)
  );
  OAI33_X1 _276_ (
    .A1(_120_),
    .A2(_084_),
    .A3(_086_),
    .B1(_087_),
    .B2(_088_),
    .B3(_107_),
    .ZN(Overflow)
  );
  OAI21_X1 _277_ (
    .A(_076_),
    .B1(_068_),
    .B2(_067_),
    .ZN(_089_)
  );
  AOI21_X1 _278_ (
    .A(_089_),
    .B1(_069_),
    .B2(_053_),
    .ZN(_090_)
  );
  OAI21_X1 _279_ (
    .A(_119_),
    .B1(_066_),
    .B2(_085_),
    .ZN(_091_)
  );
  AOI21_X1 _280_ (
    .A(_091_),
    .B1(_067_),
    .B2(_056_),
    .ZN(_092_)
  );
  AOI221_X1 _281_ (
    .A(_092_),
    .B1(_136_),
    .B2(A[7]),
    .C1(A[0]),
    .C2(_121_),
    .ZN(_093_)
  );
  OAI21_X1 _282_ (
    .A(_093_),
    .B1(_090_),
    .B2(_107_),
    .ZN(Cout)
  );
  INV_X1 _283_ (
    .A(ALU_Sel[2]),
    .ZN(_094_)
  );
  INV_X1 _284_ (
    .A(ALU_Sel[0]),
    .ZN(_095_)
  );
  INV_X1 _285_ (
    .A(ALU_Sel[1]),
    .ZN(_096_)
  );
  INV_X1 _286_ (
    .A(A[1]),
    .ZN(_097_)
  );
  INV_X1 _287_ (
    .A(A[2]),
    .ZN(_098_)
  );
  INV_X1 _288_ (
    .A(A[3]),
    .ZN(_099_)
  );
  INV_X1 _289_ (
    .A(A[4]),
    .ZN(_100_)
  );
  INV_X1 _290_ (
    .A(A[6]),
    .ZN(_101_)
  );
  INV_X1 _291_ (
    .A(B[0]),
    .ZN(_102_)
  );
  INV_X1 _292_ (
    .A(B[5]),
    .ZN(_103_)
  );
  INV_X1 _293_ (
    .A(B[7]),
    .ZN(_104_)
  );
  XOR2_X1 _294_ (
    .A(A[0]),
    .B(B[0]),
    .Z(_105_)
  );
  NOR2_X1 _295_ (
    .A1(ALU_Sel[0]),
    .A2(ALU_Sel[1]),
    .ZN(_106_)
  );
  NAND2_X1 _296_ (
    .A1(_094_),
    .A2(_106_),
    .ZN(_107_)
  );
  NAND2_X1 _297_ (
    .A1(Cin),
    .A2(_105_),
    .ZN(_108_)
  );
  XNOR2_X1 _298_ (
    .A(Cin),
    .B(_105_),
    .ZN(_109_)
  );
  NAND2_X1 _299_ (
    .A1(ALU_Sel[0]),
    .A2(ALU_Sel[1]),
    .ZN(_110_)
  );
  NOR2_X1 _300_ (
    .A1(ALU_Sel[2]),
    .A2(_110_),
    .ZN(_111_)
  );
  NAND2_X1 _301_ (
    .A1(A[0]),
    .A2(B[0]),
    .ZN(_112_)
  );
  AND2_X1 _302_ (
    .A1(ALU_Sel[2]),
    .A2(_106_),
    .ZN(_113_)
  );
  NAND2_X1 _303_ (
    .A1(ALU_Sel[2]),
    .A2(_106_),
    .ZN(_114_)
  );
  AND2_X1 _304_ (
    .A1(_112_),
    .A2(_113_),
    .ZN(_115_)
  );
  OAI22_X1 _305_ (
    .A1(A[0]),
    .A2(B[0]),
    .B1(_111_),
    .B2(_115_),
    .ZN(_116_)
  );
  NAND3_X1 _306_ (
    .A1(ALU_Sel[2]),
    .A2(ALU_Sel[0]),
    .A3(_096_),
    .ZN(_117_)
  );
  NOR2_X1 _307_ (
    .A1(A[0]),
    .A2(_117_),
    .ZN(_118_)
  );
  NOR3_X1 _308_ (
    .A1(ALU_Sel[2]),
    .A2(_095_),
    .A3(ALU_Sel[1]),
    .ZN(_119_)
  );
  NAND3_X1 _309_ (
    .A1(_094_),
    .A2(ALU_Sel[0]),
    .A3(_096_),
    .ZN(_120_)
  );
  NOR2_X1 _310_ (
    .A1(_094_),
    .A2(_110_),
    .ZN(_121_)
  );
  NAND2_X1 _311_ (
    .A1(A[1]),
    .A2(_121_),
    .ZN(_122_)
  );
  NAND2_X1 _312_ (
    .A1(_095_),
    .A2(ALU_Sel[1]),
    .ZN(_123_)
  );
  NOR2_X1 _313_ (
    .A1(ALU_Sel[2]),
    .A2(_123_),
    .ZN(_124_)
  );
  NAND3_X1 _314_ (
    .A1(_094_),
    .A2(_095_),
    .A3(ALU_Sel[1]),
    .ZN(_125_)
  );
  OAI21_X1 _315_ (
    .A(_122_),
    .B1(_125_),
    .B2(_112_),
    .ZN(_126_)
  );
  AOI211_X1 _316_ (
    .A(_118_),
    .B(_126_),
    .C1(_119_),
    .C2(_105_),
    .ZN(_127_)
  );
  OAI211_X1 _317_ (
    .A(_116_),
    .B(_127_),
    .C1(_107_),
    .C2(_109_),
    .ZN(Result[0])
  );
  XNOR2_X1 _318_ (
    .A(A[1]),
    .B(B[1]),
    .ZN(_128_)
  );
  XNOR2_X1 _319_ (
    .A(_112_),
    .B(_128_),
    .ZN(_129_)
  );
  OR2_X1 _320_ (
    .A1(_108_),
    .A2(_129_),
    .ZN(_130_)
  );
  AOI21_X1 _321_ (
    .A(_107_),
    .B1(_108_),
    .B2(_129_),
    .ZN(_131_)
  );
  OR3_X1 _322_ (
    .A1(A[0]),
    .A2(_102_),
    .A3(_128_),
    .ZN(_132_)
  );
  OAI21_X1 _323_ (
    .A(_128_),
    .B1(_102_),
    .B2(A[0]),
    .ZN(_133_)
  );
  AND2_X1 _324_ (
    .A1(_119_),
    .A2(_133_),
    .ZN(_134_)
  );
  OAI21_X1 _325_ (
    .A(_111_),
    .B1(B[1]),
    .B2(A[1]),
    .ZN(_135_)
  );
  NOR2_X1 _326_ (
    .A1(_094_),
    .A2(_123_),
    .ZN(_136_)
  );
  NAND2_X1 _327_ (
    .A1(A[1]),
    .A2(B[1]),
    .ZN(_137_)
  );
  OR2_X1 _328_ (
    .A1(_125_),
    .A2(_137_),
    .ZN(_138_)
  );
  assign Result[7] = Negative;
endmodule

(* top =  1  *)
(* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:1" *)
module alu_8bit_top(clk, rst, A, B, ALU_Sel, Cin, Result);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:4" *)
  input [7:0] A;
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:6" *)
  input [2:0] ALU_Sel;
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:11" *)
  wire [7:0] A_r;
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:5" *)
  input [7:0] B;
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:11" *)
  wire [7:0] B_r;
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:7" *)
  input Cin;
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:13" *)
  wire Cin_r;
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:8" *)
  output [7:0] Result;
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:14" *)
  wire [7:0] Result_w;
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:12" *)
  wire [2:0] Sel_r;
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:2" *)
  input clk;
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:3" *)
  input rst;
  INV_X1 _40_ (
    .A(rst),
    .ZN(_19_)
  );
  INV_X1 _41_ (
    .A(rst),
    .ZN(_00_)
  );
  INV_X1 _42_ (
    .A(rst),
    .ZN(_01_)
  );
  INV_X1 _43_ (
    .A(rst),
    .ZN(_02_)
  );
  INV_X1 _44_ (
    .A(rst),
    .ZN(_03_)
  );
  INV_X1 _45_ (
    .A(rst),
    .ZN(_04_)
  );
  INV_X1 _46_ (
    .A(rst),
    .ZN(_05_)
  );
  INV_X1 _47_ (
    .A(rst),
    .ZN(_06_)
  );
  INV_X1 _48_ (
    .A(rst),
    .ZN(_07_)
  );
  INV_X1 _49_ (
    .A(rst),
    .ZN(_08_)
  );
  INV_X1 _50_ (
    .A(rst),
    .ZN(_09_)
  );
  INV_X1 _51_ (
    .A(rst),
    .ZN(_10_)
  );
  INV_X1 _52_ (
    .A(rst),
    .ZN(_11_)
  );
  INV_X1 _53_ (
    .A(rst),
    .ZN(_12_)
  );
  INV_X1 _54_ (
    .A(rst),
    .ZN(_13_)
  );
  INV_X1 _55_ (
    .A(rst),
    .ZN(_14_)
  );
  INV_X1 _56_ (
    .A(rst),
    .ZN(_15_)
  );
  INV_X1 _57_ (
    .A(rst),
    .ZN(_16_)
  );
  INV_X1 _58_ (
    .A(rst),
    .ZN(_17_)
  );
  INV_X1 _59_ (
    .A(rst),
    .ZN(_18_)
  );
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:16" *)
  DFFR_X1 _60_ (
    .CK(clk),
    .D(A[0]),
    .Q(A_r[0]),
    .QN(_20_),
    .RN(_00_)
  );
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:16" *)
  DFFR_X1 _61_ (
    .CK(clk),
    .D(A[1]),
    .Q(A_r[1]),
    .QN(_21_),
    .RN(_01_)
  );
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:16" *)
  DFFR_X1 _62_ (
    .CK(clk),
    .D(A[2]),
    .Q(A_r[2]),
    .QN(_22_),
    .RN(_02_)
  );
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:16" *)
  DFFR_X1 _63_ (
    .CK(clk),
    .D(A[3]),
    .Q(A_r[3]),
    .QN(_23_),
    .RN(_03_)
  );
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:16" *)
  DFFR_X1 _64_ (
    .CK(clk),
    .D(A[4]),
    .Q(A_r[4]),
    .QN(_24_),
    .RN(_04_)
  );
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:16" *)
  DFFR_X1 _65_ (
    .CK(clk),
    .D(A[5]),
    .Q(A_r[5]),
    .QN(_25_),
    .RN(_05_)
  );
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:16" *)
  DFFR_X1 _66_ (
    .CK(clk),
    .D(A[6]),
    .Q(A_r[6]),
    .QN(_26_),
    .RN(_06_)
  );
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:16" *)
  DFFR_X1 _67_ (
    .CK(clk),
    .D(A[7]),
    .Q(A_r[7]),
    .QN(_27_),
    .RN(_07_)
  );
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:16" *)
  DFFR_X1 _68_ (
    .CK(clk),
    .D(ALU_Sel[0]),
    .Q(Sel_r[0]),
    .QN(_28_),
    .RN(_08_)
  );
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:16" *)
  DFFR_X1 _69_ (
    .CK(clk),
    .D(ALU_Sel[1]),
    .Q(Sel_r[1]),
    .QN(_29_),
    .RN(_09_)
  );
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:16" *)
  DFFR_X1 _70_ (
    .CK(clk),
    .D(ALU_Sel[2]),
    .Q(Sel_r[2]),
    .QN(_30_),
    .RN(_10_)
  );
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:16" *)
  DFFR_X1 _71_ (
    .CK(clk),
    .D(Cin),
    .Q(Cin_r),
    .QN(_31_),
    .RN(_11_)
  );
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:16" *)
  DFFR_X1 _72_ (
    .CK(clk),
    .D(B[0]),
    .Q(B_r[0]),
    .QN(_32_),
    .RN(_12_)
  );
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:16" *)
  DFFR_X1 _73_ (
    .CK(clk),
    .D(B[1]),
    .Q(B_r[1]),
    .QN(_33_),
    .RN(_13_)
  );
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:16" *)
  DFFR_X1 _74_ (
    .CK(clk),
    .D(B[2]),
    .Q(B_r[2]),
    .QN(_34_),
    .RN(_14_)
  );
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:16" *)
  DFFR_X1 _75_ (
    .CK(clk),
    .D(B[3]),
    .Q(B_r[3]),
    .QN(_35_),
    .RN(_15_)
  );
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:16" *)
  DFFR_X1 _76_ (
    .CK(clk),
    .D(B[4]),
    .Q(B_r[4]),
    .QN(_36_),
    .RN(_16_)
  );
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:16" *)
  DFFR_X1 _77_ (
    .CK(clk),
    .D(B[5]),
    .Q(B_r[5]),
    .QN(_37_),
    .RN(_17_)
  );
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:16" *)
  DFFR_X1 _78_ (
    .CK(clk),
    .D(B[6]),
    .Q(B_r[6]),
    .QN(_38_),
    .RN(_18_)
  );
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:16" *)
  DFFR_X1 _79_ (
    .CK(clk),
    .D(B[7]),
    .Q(B_r[7]),
    .QN(_39_),
    .RN(_19_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/bdesh/Codes/8Bit_Alu/rtl/alu_8bit_top.v:30" *)
  alu_8bit u_alu (
    .A(A_r),
    .ALU_Sel(Sel_r),
    .B(B_r),
    .Cin(Cin_r),
    .Cout(),
    .Negative(),
    .Overflow(),
    .Result(Result_w),
    .Zero()
  );
  assign Result = Result_w;
endmodule
