/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "ShiftReg4bit.v:2" *)
module shift_reg_4bit(clk, rst, din, q);
  (* src = "ShiftReg4bit.v:9" *)
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  (* src = "ShiftReg4bit.v:3" *)
  input clk;
  (* src = "ShiftReg4bit.v:5" *)
  input din;
  (* src = "ShiftReg4bit.v:6" *)
  output [3:0] q;
  (* src = "ShiftReg4bit.v:4" *)
  input rst;
  INV_X1 _09_ (
    .A(q[0]),
    .ZN(_01_)
  );
  INV_X1 _10_ (
    .A(q[1]),
    .ZN(_02_)
  );
  INV_X1 _11_ (
    .A(q[2]),
    .ZN(_03_)
  );
  INV_X1 _12_ (
    .A(din),
    .ZN(_04_)
  );
  NOR2_X1 _13_ (
    .A1(_01_),
    .A2(rst),
    .ZN(_00_[1])
  );
  NOR2_X1 _14_ (
    .A1(rst),
    .A2(_02_),
    .ZN(_00_[2])
  );
  NOR2_X1 _15_ (
    .A1(rst),
    .A2(_03_),
    .ZN(_00_[3])
  );
  NOR2_X1 _16_ (
    .A1(rst),
    .A2(_04_),
    .ZN(_00_[0])
  );
  (* src = "ShiftReg4bit.v:9" *)
  DFF_X1 _17_ (
    .CK(clk),
    .D(_00_[0]),
    .Q(q[0]),
    .QN(_05_)
  );
  (* src = "ShiftReg4bit.v:9" *)
  DFF_X1 _18_ (
    .CK(clk),
    .D(_00_[1]),
    .Q(q[1]),
    .QN(_06_)
  );
  (* src = "ShiftReg4bit.v:9" *)
  DFF_X1 _19_ (
    .CK(clk),
    .D(_00_[2]),
    .Q(q[2]),
    .QN(_07_)
  );
  (* src = "ShiftReg4bit.v:9" *)
  DFF_X1 _20_ (
    .CK(clk),
    .D(_00_[3]),
    .Q(q[3]),
    .QN(_08_)
  );
endmodule
